from dsi2dsio.src.util import (make_first_letter_lowercase,
                               parse_dsi_unit,
                               parse_qudt_quantitykind,
                               update_prefixes,
                               make_first_letter_uppercase,
                               mapping,
                               prefixes,
                               expand_prefix,
                               elt_is_in_namespace,
                               get_si_unit_expression,
                               create_uri_ref)
